//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TwitterDbEntities1 : DbContext
    {
        public TwitterDbEntities1()
            : base("name=TwitterDbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tm_person> tm_person { get; set; }
        public virtual DbSet<tm_tweets> tm_tweets { get; set; }
        public virtual DbSet<tx_following> tx_following { get; set; }
    
        public virtual ObjectResult<usp_fetch_profile_det_Result> usp_fetch_profile_det(string pUserID)
        {
            var pUserIDParameter = pUserID != null ?
                new ObjectParameter("pUserID", pUserID) :
                new ObjectParameter("pUserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_fetch_profile_det_Result>("usp_fetch_profile_det", pUserIDParameter);
        }
    
        public virtual int usp_profile_actions(string pUserID, string pAction, string pEmailId, string pFullName)
        {
            var pUserIDParameter = pUserID != null ?
                new ObjectParameter("pUserID", pUserID) :
                new ObjectParameter("pUserID", typeof(string));
    
            var pActionParameter = pAction != null ?
                new ObjectParameter("pAction", pAction) :
                new ObjectParameter("pAction", typeof(string));
    
            var pEmailIdParameter = pEmailId != null ?
                new ObjectParameter("pEmailId", pEmailId) :
                new ObjectParameter("pEmailId", typeof(string));
    
            var pFullNameParameter = pFullName != null ?
                new ObjectParameter("pFullName", pFullName) :
                new ObjectParameter("pFullName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_profile_actions", pUserIDParameter, pActionParameter, pEmailIdParameter, pFullNameParameter);
        }
    
        public virtual int usp_signup(string pUserID, string pPassword, string pEmailId, string pFullName)
        {
            var pUserIDParameter = pUserID != null ?
                new ObjectParameter("pUserID", pUserID) :
                new ObjectParameter("pUserID", typeof(string));
    
            var pPasswordParameter = pPassword != null ?
                new ObjectParameter("pPassword", pPassword) :
                new ObjectParameter("pPassword", typeof(string));
    
            var pEmailIdParameter = pEmailId != null ?
                new ObjectParameter("pEmailId", pEmailId) :
                new ObjectParameter("pEmailId", typeof(string));
    
            var pFullNameParameter = pFullName != null ?
                new ObjectParameter("pFullName", pFullName) :
                new ObjectParameter("pFullName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_signup", pUserIDParameter, pPasswordParameter, pEmailIdParameter, pFullNameParameter);
        }
    
        public virtual int usp_tweets_actions(string pUserID, string pAction, Nullable<int> pTweet_Id, string pMesage)
        {
            var pUserIDParameter = pUserID != null ?
                new ObjectParameter("pUserID", pUserID) :
                new ObjectParameter("pUserID", typeof(string));
    
            var pActionParameter = pAction != null ?
                new ObjectParameter("pAction", pAction) :
                new ObjectParameter("pAction", typeof(string));
    
            var pTweet_IdParameter = pTweet_Id.HasValue ?
                new ObjectParameter("pTweet_Id", pTweet_Id) :
                new ObjectParameter("pTweet_Id", typeof(int));
    
            var pMesageParameter = pMesage != null ?
                new ObjectParameter("pMesage", pMesage) :
                new ObjectParameter("pMesage", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_tweets_actions", pUserIDParameter, pActionParameter, pTweet_IdParameter, pMesageParameter);
        }
    
        public virtual int usp_update_profile(string pUserID, string pEmailId, string pFullName)
        {
            var pUserIDParameter = pUserID != null ?
                new ObjectParameter("pUserID", pUserID) :
                new ObjectParameter("pUserID", typeof(string));
    
            var pEmailIdParameter = pEmailId != null ?
                new ObjectParameter("pEmailId", pEmailId) :
                new ObjectParameter("pEmailId", typeof(string));
    
            var pFullNameParameter = pFullName != null ?
                new ObjectParameter("pFullName", pFullName) :
                new ObjectParameter("pFullName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_update_profile", pUserIDParameter, pEmailIdParameter, pFullNameParameter);
        }
    
        public virtual int usp_validatelogin(string pUserID, string pPassword, ObjectParameter responseMessage)
        {
            var pUserIDParameter = pUserID != null ?
                new ObjectParameter("pUserID", pUserID) :
                new ObjectParameter("pUserID", typeof(string));
    
            var pPasswordParameter = pPassword != null ?
                new ObjectParameter("pPassword", pPassword) :
                new ObjectParameter("pPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_validatelogin", pUserIDParameter, pPasswordParameter, responseMessage);
        }
    
        public virtual int usp_follow_profile(string pProfileId, string pUserID, string pFollow)
        {
            var pProfileIdParameter = pProfileId != null ?
                new ObjectParameter("pProfileId", pProfileId) :
                new ObjectParameter("pProfileId", typeof(string));
    
            var pUserIDParameter = pUserID != null ?
                new ObjectParameter("pUserID", pUserID) :
                new ObjectParameter("pUserID", typeof(string));
    
            var pFollowParameter = pFollow != null ?
                new ObjectParameter("pFollow", pFollow) :
                new ObjectParameter("pFollow", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_follow_profile", pProfileIdParameter, pUserIDParameter, pFollowParameter);
        }
    }
}
