//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_tweets
    {
        public int tweet_Id { get; set; }
        public string UserId { get; set; }
        public string message { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual tm_person tm_person { get; set; }
    }
}
